stages:
  - test
  - build
  - deploy

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

Build Website Container:
  stage: build
  image: docker:latest
  services:
    - docker:latest
  script:
    - docker build -t registry.gitlab.com/agbaraka/website:latest -t registry.gitlab.com/agbaraka/website:${CI_COMMIT_SHA} .
    - echo "$CI_JOB_TOKEN" | docker login registry.gitlab.com -u "gitlab-ci-token" --password-stdin
    - docker push registry.gitlab.com/agbaraka/website:latest
    - docker push registry.gitlab.com/agbaraka/website:${CI_COMMIT_SHA}


Deploy Website Container:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [ "" ]
  script:
    - kubectl apply -f ./k8s.yml
    - kubectl set image deployment/my-website-deployment my-website=registry.gitlab.com/agbaraka/website:${CI_COMMIT_SHA}
    - kubectl rollout status deployment/my-website-deployment
