apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-website-pod
  template:
    metadata:
      labels:
        name: my-website-pod
    spec:
      containers:
        - name: my-website
          image: registry.gitlab.com/agbaraka/website
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-website-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: my-website-pod