name: Build & Deployment Website

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
        
      - name: Build and Minify with Hugo
        run: hugo --minify

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}